<?php

namespace Belsignum\ViteCritical\Xclass\Service;

use Belsignum\ViteCritical\Domain\Model\ViteManifestItem;
use Praetorius\ViteAssetCollector\Exception\ViteException;
use Belsignum\ViteCritical\Domain\Model\ViteManifest;
use Psr\Http\Message\ServerRequestInterface;
use TYPO3\CMS\Core\Cache\Frontend\FrontendInterface;
use TYPO3\CMS\Core\Configuration\ExtensionConfiguration;
use TYPO3\CMS\Core\Core\Environment;
use TYPO3\CMS\Core\Http\ApplicationType;
use TYPO3\CMS\Core\Http\ServerRequest;
use TYPO3\CMS\Core\Package\PackageManager;
use TYPO3\CMS\Core\Page\AssetCollector;
use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController;

class ViteService extends \Praetorius\ViteAssetCollector\Service\ViteService
{
    private FrontendInterface $cache;
    private ServerRequest $request;
    private array $configuration;
    private array $viteCriticalCssConfig;

    public function __construct(
        FrontendInterface      $cache,
        AssetCollector         $assetCollector,
        PackageManager         $packageManager,
        ExtensionConfiguration $extensionConfiguration
    )
    {
        parent::__construct($cache, $assetCollector, $packageManager, $extensionConfiguration);

        $this->cache = $cache;
    }

    private function isFrontend()
    {
        return (($this->request ?? null) instanceof ServerRequestInterface
            && ApplicationType::fromRequest($this->request)->isFrontend());
    }

    public function addAssetsFromManifest(
        string $manifestFile,
        string $entry,
        bool   $addCss = true,
        array  $assetOptions = [],
        array  $scriptTagAttributes = [],
        array  $cssTagAttributes = []
    ): void
    {
        $this->request = $GLOBALS['TYPO3_REQUEST'];
        if ($this->isFrontend())
        {
            $site = $this->request->getAttribute('site');
            if($site)
            {
                $this->configuration = $site->getConfiguration();
            }
        }

        $entry = $this->determineAssetIdentifierFromExtensionPath($entry);

        $manifestFile = $this->resolveManifestFile($manifestFile);
        $outputDir = $this->determineOutputDirFromManifestFile($manifestFile);
        $manifest = $this->parseExtendedManifestFile($manifestFile);

        if (!$manifest->get($entry)?->isEntry)
        {
            throw new ViteException(sprintf(
                'Invalid vite entry point "%s" in manifest file "%s".',
                $entry,
                $manifestFile
            ), 1683200524);
        }

        // The "external" flag has been introduced with TYPO3 v13. It allows bypassing
        // of the default path preparation by AssetRenderer, including the addition of
        // cache-busting parameters to all asset files. As this is not necessary for files
        // generated by vite, which already contain a hash in their file name, this behavior
        // is avoided with v13. This also improves the behavior of dynamic imports, which
        // could result in duplicate requests before.
        $assetOptions = [
            'external' => $this->useExternalFlag(),
            ...$assetOptions
        ];

        $entryPoint = $manifest->get($entry);

        if (!$entryPoint->isCss())
        {
            $scriptTagAttributes = $this->prepareScriptAttributes($scriptTagAttributes);

            $this->assetCollector->addJavaScript(
                "vite:{$entry}",
                $this->prepareAssetPath($outputDir . $entryPoint->file, $assetOptions['external']),
                [
                    'type' => 'module',
                    ...$scriptTagAttributes
                ],
                $assetOptions
            );
        }

        if ($addCss)
        {
            $isFrontend = $this->isFrontend();
            $isCriticalCssEnabled = $this->isCriticalCssEnabledByConfig();
            $hasCritical = $this->hasCritical($entryPoint);
            $requestIsPartOfConfig = $this->requestIsPartOfConfig($entryPoint->name);

            if($isFrontend && $isCriticalCssEnabled && $hasCritical && $requestIsPartOfConfig)
            {
                // Add critical
                $criticalFile = $this->getCriticalCss($entryPoint);

                $absPath = $this->prepareAssetPath($outputDir . $criticalFile, $assetOptions['external']);
                $content = file_get_contents($absPath);
                $inlineAttributes = [
                    'type' => 'text/css',
                    'data-type' => 'critical-css'
                ];
                $additionalAttributes = $this->getCriticalAdditionalAttributes($entryPoint->name);
                if (!empty($additionalAttributes)) {
                    $inlineAttributes = array_merge($inlineAttributes, $additionalAttributes);
                }
                $this->assetCollector->addInlineStyleSheet(
                    "viteCritical:critical-{$entry}",
                    $content,
                    $inlineAttributes,
                    ['priority' => true]
                );

                $staleCssAttributes = [
                    'rel' => 'preload',
                    'as' => 'style',
                    'onload' => "this.onload=null;this.rel='stylesheet';document.querySelector('style[data-type=\"critical-css\"]').type='stale/css';",
                    'data-noscript' => 'true'
                ];

                if (!empty($entryPoint->file) && $entryPoint->isCss()) {
                    $this->assetCollector->addStyleSheet(
                        "vite:{$entry}:main",
                        $this->prepareAssetPath($outputDir . $entryPoint->file, $assetOptions['external']),
                        $staleCssAttributes,
                        ['priority' => false]
                    );
                    // todo: add noscript wrap via PageRenderer hook or event (data-noscript="true")
                }

                foreach ($entryPoint->css as $file)
                {
                    $this->assetCollector->addStyleSheet(
                        "vite:{$entry}:{$file}",
                        $this->prepareAssetPath($outputDir . $file, $assetOptions['external']),
                        $staleCssAttributes,
                        ['priority' => false]
                    );
                    // todo: add noscript wrap via PageRenderer hook or event (data-noscript="true")
                }
            }
            else
            {

                if ($entryPoint->isCss())
                {
                    $this->assetCollector->addStyleSheet(
                        "vite:{$entry}",
                        $this->prepareAssetPath($outputDir . $entryPoint->file, $assetOptions['external']),
                        $cssTagAttributes,
                        $assetOptions
                    );
                }

                $cssTagAttributes = $this->prepareCssAttributes($cssTagAttributes);

                foreach ($manifest->getImportsForEntrypoint($entry, true) as $import)
                {
                    $identifier = md5($import->identifier . '|' . serialize($cssTagAttributes));
                    foreach ($import->css as $file)
                    {
                        $this->assetCollector->addStyleSheet(
                            "vite:{$identifier}:{$file}",
                            $this->prepareAssetPath($outputDir . $file, $assetOptions['external']),
                            $cssTagAttributes,
                            $assetOptions
                        );
                    }
                }

                foreach ($manifest->get($entry)->css as $file)
                {
                    $this->assetCollector->addStyleSheet(
                        "vite:{$entry}:{$file}",
                        $this->prepareAssetPath($outputDir . $file, $assetOptions['external']),
                        $cssTagAttributes,
                        $assetOptions
                    );
                }
            }
        }
    }

    private function parseExtendedManifestFile(string $manifestFile): ViteManifest
    {
        $cacheIdentifier = md5($manifestFile);
        $manifest = $this->cache->get($cacheIdentifier);
        if ($manifest === false)
        {
            $manifest = ViteManifest::fromFile($manifestFile);
            $this->cache->set($cacheIdentifier, $manifest);
        }
        return $manifest;
    }

    private function isCriticalCssEnabledByConfig(): bool
    {
        $viteCriticalCssConfig = $this->configuration['viteCritical']['criticalCss'] ?? [];
        if ($viteCriticalCssConfig['enable'] ?? false)
        {
            $this->viteCriticalCssConfig = $viteCriticalCssConfig;
            $simulateDev = (bool)(getenv('VITE_ASSET_COLLECTOR_SIMULATE_APPLICATION_CONTEXT_DEVELOPMENT') ?? 0);
            if ($simulateDev)
            {
                // this env param is only set to go into Development to simulate the production with dev vars
                return true;
            }
            if (Environment::getContext()->isDevelopment() === false)
            {
                return true;
            }

            $variants = $this->viteCriticalCssConfig['variants'] ?? [];
            if (empty($variants) === false)
            {
                $applicationContext = Environment::getContext()->__toString();
                foreach ($variants as $variant)
                {
                    if (!empty($variant['condition']) && str_contains($variant['condition'], $applicationContext))
                    {
                        return $variant['enable'];
                    }
                }
            }
        }
        return false;
    }

    private function requestIsPartOfConfig(?string $name): bool
    {
        $config = $this->getCriticalConfigForEntryPoint($name);
        if ($config === null) {
            return false;
        }

        $pids = $this->getCriticalPidsFromConfig($config);
        if (empty($pids)) {
            return false;
        }

        /** @var TypoScriptFrontendController $frontendController */
        $frontendController = $this->request->getAttribute('frontend.controller');
        return in_array($frontendController->id, $pids, true) || in_array($frontendController->contentPid, $pids, true);
    }

    private function getCriticalAdditionalAttributes(?string $name): array
    {
        $config = $this->getCriticalConfigForEntryPoint($name);
        if ($config === null) {
            return [];
        }

        $additionalAttributes = $config['additionalAttributes'] ?? [];
        if (!is_array($additionalAttributes) || empty($additionalAttributes)) {
            return [];
        }

        $filtered = [];
        foreach ($additionalAttributes as $key => $value) {
            if (!is_string($key) || $key === '' || !is_string($value) || $value === '') {
                continue;
            }
            if ($key === 'type' || $key === 'data-type') {
                continue;
            }
            $filtered[$key] = $value;
        }

        return $filtered;
    }

    private function getCriticalPidsFromConfig(array $config): array
    {
        $pids = $config['pids'] ?? '';
        if (is_string($pids)) {
            return GeneralUtility::intExplode(',', $pids, true);
        }
        if (is_array($pids)) {
            $pids = array_map('intval', $pids);
            return array_values(array_filter($pids, static fn (int $pid): bool => $pid > 0));
        }

        return [];
    }

    private function getCriticalConfigForEntryPoint(?string $name): ?array
    {
        $entryPointForPid = $this->viteCriticalCssConfig['entryPointForPid'] ?? [];
        if (empty($entryPointForPid) || $name === null) {
            return null;
        }

        /** @var \TYPO3\CMS\Core\Site\Entity\Site $site */
        $site = $this->request->getAttribute('site');
        $siteIdentifier = $site ? $site->getIdentifier() : '';

        foreach (array_keys($entryPointForPid) as $configKey) {
            $expectedName = sprintf('%s_%s_css', $siteIdentifier, $configKey);
            if ($name === $expectedName) {
                $configEntry = $entryPointForPid[$configKey];
                if (is_array($configEntry)) {
                    return $configEntry;
                }
                return ['pids' => $configEntry];
            }
        }

        return null;
    }

    private function hasCritical(ViteManifestItem $entry): bool
    {
        if ($entry->critical !== '') {
            return true;
        }

        if (!empty($entry->criticalByPid)) {
            /** @var TypoScriptFrontendController $frontendController */
            $frontendController = $this->request->getAttribute('frontend.controller');
            $pid = (string)$frontendController->id;
            return isset($entry->criticalByPid[$pid]);
        }

        return false;
    }

    private function getCriticalCss(ViteManifestItem $entry): string
    {
        /** @var TypoScriptFrontendController $frontendController */
        $frontendController = $this->request->getAttribute('frontend.controller');
        $pid = (string)$frontendController->id;

        if (isset($entry->criticalByPid[$pid])) {
            return $entry->criticalByPid[$pid];
        }

        return $entry->critical;
    }

    private function hasDeferred(ViteManifestItem $entry): bool
    {
        return $entry->deferred !== '';
    }

    private function getDeferredCss(ViteManifestItem $entry): string
    {
        return $entry->critical;
    }



}
